"use client";
import {useEffect,useRef,useState} from 'react';
import {SpeechExperiment,Config,Event} from '../../lib/speech-experiment';
export default function SpeechTest(){
 const [connection,setConnection]=useState('Connecting…'); const [config,setConfig]=useState<Config|null>(null);const [status,setStatus]=useState('Waiting for a Godot test attempt');const [partial,setPartial]=useState('');const [final,setFinal]=useState('');const [details,setDetails]=useState<Event>({});
 const [connected,setConnected]=useState(false);const [active,setActive]=useState(false);const [supported,setSupported]=useState<boolean|null>(null);const [history,setHistory]=useState<string[]>([]);const [sent,setSent]=useState(0);
 function log(message:string){setHistory(old=>[new Date().toLocaleTimeString()+' — '+message,...old].slice(0,20));}
 const engine=useRef<SpeechExperiment|null>(null);const socket=useRef<WebSocket|null>(null);const events=useRef<Event[]>([]);const attempts=useRef<Event[]>([]);
 useEffect(()=>{
  setSupported('SpeechRecognition' in window || 'webkitSpeechRecognition' in window);
  const relay=new URLSearchParams(location.hash.slice(1)).get('relay');
  if(!relay){setConnection('Open this page using the DEBUG browser button in Godot.');return;}
  let url:URL;try{url=new URL(relay);if(!['wss:','ws:'].includes(url.protocol)||(location.protocol==='https:'&&url.protocol!=='wss:'))throw Error();}catch{setConnection('Invalid relay address');return;}
  const ws=socket.current=new WebSocket(url);const capture=engine.current=new SpeechExperiment(event=>{events.current.push(event);setDetails(event);log(String(event.error||event.status||event.transcript||event.type));if(event.type==='speech_error'&&!event.recoverable)setActive(false);if(event.type==='speech_result'){if(event.is_final){setFinal(String(event.transcript));setPartial('');}else setPartial(String(event.transcript));}else setStatus(String(event.error||event.status));if(ws.readyState===WebSocket.OPEN){ws.send(JSON.stringify(event));if(event.type==='speech_result')setSent(n=>n+1);}});
  ws.onopen=()=>{setConnected(true);setConnection('Relay connected');log('Relay connected');ws.send(JSON.stringify({kind:'hello',role:'speech_client'}));};
  ws.onmessage=e=>{let m;try{m=JSON.parse(e.data);}catch{return;}if(m.type==='speech_control'){capture.stop();setActive(false);log(m.action==='start'?'Game requested a speaking turn':'Game ended the speaking turn');setPartial('');setFinal('');setConfig(m.action==='start'?m:null);setStatus(m.action==='start'?'Ready — click Start microphone':'Attempt stopped');}else if(m.type==='speech_attempt'){attempts.current.push(m.attempt);}else if(m.type==='speech_observation'){events.current.push(m.event);setDetails(m.event);}};
  ws.onerror=()=>setConnection('Relay connection error');ws.onclose=e=>{capture.stop();setActive(false);setConnected(false);setConfig(null);setConnection('Disconnected — reopen from Godot');log('Relay closed (code '+e.code+'). Stop this game run, close old microphone tabs, then connect and reopen from Godot.');};
  const timer=setInterval(()=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({kind:'ping'}));},30000);
  return()=>{clearInterval(timer);capture.stop();ws.close();};
 },[]);
 function save(){const url=URL.createObjectURL(new Blob([JSON.stringify({attempts:attempts.current,events:events.current},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='speech-browser-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const buttonStyle = {padding:'12px 18px',border:'2px solid #aaa6db',borderRadius:8,background:'#34304f',color:'#fff',fontSize:16,cursor:'pointer'};
 return <main style={{maxWidth:850,margin:'auto',padding:24,color:'#eee',background:'#171728',minHeight:'100vh',overflowWrap:'anywhere'}}><h1>DEBUG — Speech comparison</h1><p>{connection}</p><p>Start a speaking turn or test attempt in Godot, then click Start microphone here. Keep this page open on the computer whose microphone you want to use.</p><p>Microphone audio may be processed by your browser’s speech provider. Text passes through your game relay. This tool saves text, not audio.</p><p>Language: {config?.language||'—'} · Phrase bias requested: {config?.bias_enabled?'yes':'no'}</p><div style={{display:"flex",gap:12,flexWrap:"wrap",margin:"20px 0"}}><button style={{...buttonStyle,background:config&&connected&&supported&&!active?"#e72bbd":"#494657",opacity:config&&connected&&supported&&!active?1:0.55,cursor:config&&connected&&supported&&!active?"pointer":"not-allowed"}} disabled={!config||!connected||!supported||active} onClick={()=>{if(config){setActive(true);setStatus('Starting — allow microphone access if prompted');log('Start microphone clicked');engine.current?.start(config);}}}>Start microphone</button>{' '}<button style={{...buttonStyle,opacity:active?1:0.5}} disabled={!active} onClick={()=>{engine.current?.stop();setActive(false);log('Microphone stopped by you');setStatus('Microphone stopped');}}>Stop microphone</button>{' '}<button style={buttonStyle} onClick={save}>Export JSON</button></div><section aria-live="polite" style={{border:'2px solid #aaa6db',padding:16,margin:'16px 0',background:'#25253d'}}><strong>Microphone: {status}</strong><p>{!connected?'Start is disabled: the relay is disconnected. Stop the game, close old microphone tabs, then reconnect and reopen from Godot.':!supported?'Start is disabled: this browser does not expose Web Speech recognition. Open the paired link in Chrome to test.':!config?'Start is disabled: waiting for a speaking turn from Godot. Click Speak in the game.':active?'Microphone start requested. Check the events below for audio capture and recognition.':'Ready: click the pink Start microphone button above.'}</p><p>Recognition results sent to relay: {sent} (delivery to Godot is not confirmed by this counter).</p></section><h2>While speaking</h2><p>{partial||'—'}</p><h2>Final words</h2><p>{final||'—'}</p><details open><summary>Connection and microphone events</summary><ol>{history.map((line,i)=><li key={i}>{line}</li>)}</ol></details><details open><summary>Alternatives, confidence and errors</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(details,null,2)}</pre></details><p>If recognition is unavailable in this browser, try a supported browser explicitly. No recognition service is switched automatically.</p></main>;
}
